-- ============================================================
-- MILAGRES PMS — Seed: property guides + regional knowledge base
-- Run AFTER 011_property_guides_kb.sql. Idempotent (re-runnable).
-- Source: 'Guia de Boas-Vindas' PDFs (Dez/2024).
-- ============================================================

DO $$
DECLARE cid uuid := 'a0000000-0000-0000-0000-000000000001';
BEGIN

-- Reset previously seeded KB rows (tagged) so re-running is clean.
DELETE FROM public.kb_articles WHERE company_id = cid AND tags @> ARRAY['seed:guia_v1'];

INSERT INTO public.property_guides (company_id, unit_code, name, property_type, condo, region, max_guests, suites, beds, bathrooms, short_description, description, amenities, house_rules, check_in_time, check_out_time, cancellation_policy, wifi_ssid, wifi_password, access_method, door_code, access_instructions)
VALUES (cid, 'cotinguiba-08', 'Cotinguiba 08', 'duplex', 'Cotinguiba', 'São Miguel dos Milagres', 6, 2, '2 camas queen + 2 bicama', '2 banheiros + 1 lavabo', 'Dúplex moderno a poucos passos da praia, com piscina privativa.', 'Dúplex a passos do mar, ideal para momentos de conforto e lazer. Acomoda até 6 pessoas em 2 suítes.', ARRAY['2 suíte(s) com ar-condicionado', 'Sala de TV', 'Internet de alta velocidade em toda a casa', 'Cozinha totalmente equipada', 'Piscina privativa', 'Churrasqueira portátil a carvão']::text[], ARRAY['Proibido som alto', 'Proibido animais na piscina', 'Proibido fumar', 'Proibido fazer festas', 'Proibido acumular lixo na acomodação', 'O descumprimento das regras pode gerar multa']::text[], '15:00', '11:00', 'Não reembolsável.', 'Cotinguiba 08', '08cotinguiba', 'fechadura_facial', '172839#', 'Check-in a partir das 15h. Estacione em uma vaga livre em frente ao condomínio, vá à portaria com fechadura inteligente facial, posicione o rosto na câmera e a porta destrava. Senha da fechadura eletrônica do apartamento: 172839# (sempre com # no final). Check-out às 11h.')
ON CONFLICT (company_id, unit_code) DO UPDATE SET
  name = EXCLUDED.name, property_type = EXCLUDED.property_type, condo = EXCLUDED.condo, region = EXCLUDED.region, max_guests = EXCLUDED.max_guests, suites = EXCLUDED.suites, beds = EXCLUDED.beds, bathrooms = EXCLUDED.bathrooms, short_description = EXCLUDED.short_description, description = EXCLUDED.description, amenities = EXCLUDED.amenities, house_rules = EXCLUDED.house_rules, check_in_time = EXCLUDED.check_in_time, check_out_time = EXCLUDED.check_out_time, cancellation_policy = EXCLUDED.cancellation_policy, wifi_ssid = EXCLUDED.wifi_ssid, wifi_password = EXCLUDED.wifi_password, access_method = EXCLUDED.access_method, door_code = EXCLUDED.door_code, access_instructions = EXCLUDED.access_instructions, updated_at = now();

INSERT INTO public.property_guides (company_id, unit_code, name, property_type, condo, region, max_guests, suites, beds, bathrooms, short_description, description, amenities, house_rules, check_in_time, check_out_time, cancellation_policy, wifi_ssid, wifi_password, access_method, door_code, access_instructions)
VALUES (cid, 'duplex-kanui-116', 'Duplex (Kanui 116)', 'duplex', 'Kanui', 'São Miguel dos Milagres', 10, 3, '3 camas queen + 3 bicama', '4 banheiros', 'Dúplex amplo com bela área gourmet e piscina privativa.', 'Dúplex ideal para momentos de conforto e lazer, com bela área gourmet. Acomoda até 10 pessoas em 3 suítes.', ARRAY['3 suíte(s) com ar-condicionado', 'Sala de TV', 'Internet de alta velocidade em toda a casa', 'Cozinha totalmente equipada', 'Área gourmet com piscina privativa', 'Churrasqueira a carvão']::text[], ARRAY['Proibido som alto', 'Proibido animais na piscina', 'Proibido fumar', 'Proibido fazer festas', 'Proibido acumular lixo na acomodação', 'O descumprimento das regras pode gerar multa']::text[], '15:00', '11:00', 'Não reembolsável.', 'Kanui116', '116@kanui', 'chaves_portaria', NULL, 'Check-in a partir das 15h. Retire as chaves na portaria apresentando os dados da reserva. No check-out (11h), recolha os pertences e entregue as chaves na portaria.')
ON CONFLICT (company_id, unit_code) DO UPDATE SET
  name = EXCLUDED.name, property_type = EXCLUDED.property_type, condo = EXCLUDED.condo, region = EXCLUDED.region, max_guests = EXCLUDED.max_guests, suites = EXCLUDED.suites, beds = EXCLUDED.beds, bathrooms = EXCLUDED.bathrooms, short_description = EXCLUDED.short_description, description = EXCLUDED.description, amenities = EXCLUDED.amenities, house_rules = EXCLUDED.house_rules, check_in_time = EXCLUDED.check_in_time, check_out_time = EXCLUDED.check_out_time, cancellation_policy = EXCLUDED.cancellation_policy, wifi_ssid = EXCLUDED.wifi_ssid, wifi_password = EXCLUDED.wifi_password, access_method = EXCLUDED.access_method, door_code = EXCLUDED.door_code, access_instructions = EXCLUDED.access_instructions, updated_at = now();

INSERT INTO public.property_guides (company_id, unit_code, name, property_type, condo, region, max_guests, suites, beds, bathrooms, short_description, description, amenities, house_rules, check_in_time, check_out_time, cancellation_policy, wifi_ssid, wifi_password, access_method, door_code, access_instructions)
VALUES (cid, 'kanui-201', 'Kanui 201', 'cobertura', 'Kanui', 'São Miguel dos Milagres', 10, 3, '3 camas queen + 3 bicama', '3 banheiros', 'Cobertura com área gourmet e piscina privativa.', 'Cobertura ideal para momentos de conforto e lazer, com área gourmet. Acomoda até 10 pessoas em 3 suítes.', ARRAY['3 suíte(s) com ar-condicionado', 'Sala de TV', 'Internet de alta velocidade em toda a casa', 'Cozinha totalmente equipada', 'Área gourmet com piscina privativa', 'Churrasqueira a carvão']::text[], ARRAY['Proibido som alto', 'Proibido animais na piscina', 'Proibido fumar', 'Proibido fazer festas', 'Proibido acumular lixo na acomodação', 'O descumprimento das regras pode gerar multa']::text[], '15:00', '11:00', 'Não reembolsável.', 'Kanui201', '@kanui201', 'chaves_portaria', NULL, 'Check-in a partir das 15h. Retire as chaves na portaria apresentando os dados da reserva. No check-out (11h), entregue as chaves na portaria.')
ON CONFLICT (company_id, unit_code) DO UPDATE SET
  name = EXCLUDED.name, property_type = EXCLUDED.property_type, condo = EXCLUDED.condo, region = EXCLUDED.region, max_guests = EXCLUDED.max_guests, suites = EXCLUDED.suites, beds = EXCLUDED.beds, bathrooms = EXCLUDED.bathrooms, short_description = EXCLUDED.short_description, description = EXCLUDED.description, amenities = EXCLUDED.amenities, house_rules = EXCLUDED.house_rules, check_in_time = EXCLUDED.check_in_time, check_out_time = EXCLUDED.check_out_time, cancellation_policy = EXCLUDED.cancellation_policy, wifi_ssid = EXCLUDED.wifi_ssid, wifi_password = EXCLUDED.wifi_password, access_method = EXCLUDED.access_method, door_code = EXCLUDED.door_code, access_instructions = EXCLUDED.access_instructions, updated_at = now();

INSERT INTO public.property_guides (company_id, unit_code, name, property_type, condo, region, max_guests, suites, beds, bathrooms, short_description, description, amenities, house_rules, check_in_time, check_out_time, cancellation_policy, wifi_ssid, wifi_password, access_method, door_code, access_instructions)
VALUES (cid, 'kanui-206', 'Kanui 206', 'cobertura', 'Kanui', 'São Miguel dos Milagres', 10, 3, '3 camas queen + 3 bicama', '3 banheiros', 'Cobertura com área gourmet e piscina privativa.', 'Cobertura ideal para momentos de conforto e lazer, com área gourmet. Acomoda até 10 pessoas em 3 suítes.', ARRAY['3 suíte(s) com ar-condicionado', 'Sala de TV', 'Internet de alta velocidade em toda a casa', 'Cozinha totalmente equipada', 'Área gourmet com piscina privativa', 'Churrasqueira a carvão']::text[], ARRAY['Proibido som alto', 'Proibido animais na piscina', 'Proibido fumar', 'Proibido fazer festas', 'Proibido acumular lixo na acomodação', 'O descumprimento das regras pode gerar multa']::text[], '15:00', '11:00', 'Não reembolsável.', 'Kanui206', '@kanui206', 'chaves_portaria', NULL, 'Check-in a partir das 15h. Retire as chaves na portaria apresentando os dados da reserva. No check-out (11h), entregue as chaves na portaria.')
ON CONFLICT (company_id, unit_code) DO UPDATE SET
  name = EXCLUDED.name, property_type = EXCLUDED.property_type, condo = EXCLUDED.condo, region = EXCLUDED.region, max_guests = EXCLUDED.max_guests, suites = EXCLUDED.suites, beds = EXCLUDED.beds, bathrooms = EXCLUDED.bathrooms, short_description = EXCLUDED.short_description, description = EXCLUDED.description, amenities = EXCLUDED.amenities, house_rules = EXCLUDED.house_rules, check_in_time = EXCLUDED.check_in_time, check_out_time = EXCLUDED.check_out_time, cancellation_policy = EXCLUDED.cancellation_policy, wifi_ssid = EXCLUDED.wifi_ssid, wifi_password = EXCLUDED.wifi_password, access_method = EXCLUDED.access_method, door_code = EXCLUDED.door_code, access_instructions = EXCLUDED.access_instructions, updated_at = now();

INSERT INTO public.property_guides (company_id, unit_code, name, property_type, condo, region, max_guests, suites, beds, bathrooms, short_description, description, amenities, house_rules, check_in_time, check_out_time, cancellation_policy, wifi_ssid, wifi_password, access_method, door_code, access_instructions)
VALUES (cid, 'tamona-07', 'Tamoná 07', 'casa_terrea', 'Tamoná', 'São Miguel dos Milagres', 6, 2, '2 camas queen + 2 bicama', '2 banheiros', 'Casa térrea a passos do mar com piscina privativa.', 'Casa térrea a passos do mar, ideal para conforto e lazer. Acomoda até 6 pessoas em 2 suítes.', ARRAY['2 suíte(s) com ar-condicionado', 'Sala de TV', 'Internet de alta velocidade em toda a casa', 'Cozinha totalmente equipada', 'Piscina privativa', 'Churrasqueira portátil a carvão']::text[], ARRAY['Proibido som alto', 'Proibido animais na piscina', 'Proibido fumar', 'Proibido fazer festas', 'Proibido acumular lixo na acomodação', 'O descumprimento das regras pode gerar multa']::text[], '15:00', '11:00', 'Não reembolsável.', 'TAMONA07', 'tamona07', 'chaves_cofre', NULL, 'Check-in a partir das 15h. As chaves ficam no cofre da acomodação; nossa equipe envia o código pelo WhatsApp. No check-out (11h), recoloque as chaves no cofre.')
ON CONFLICT (company_id, unit_code) DO UPDATE SET
  name = EXCLUDED.name, property_type = EXCLUDED.property_type, condo = EXCLUDED.condo, region = EXCLUDED.region, max_guests = EXCLUDED.max_guests, suites = EXCLUDED.suites, beds = EXCLUDED.beds, bathrooms = EXCLUDED.bathrooms, short_description = EXCLUDED.short_description, description = EXCLUDED.description, amenities = EXCLUDED.amenities, house_rules = EXCLUDED.house_rules, check_in_time = EXCLUDED.check_in_time, check_out_time = EXCLUDED.check_out_time, cancellation_policy = EXCLUDED.cancellation_policy, wifi_ssid = EXCLUDED.wifi_ssid, wifi_password = EXCLUDED.wifi_password, access_method = EXCLUDED.access_method, door_code = EXCLUDED.door_code, access_instructions = EXCLUDED.access_instructions, updated_at = now();

INSERT INTO public.property_guides (company_id, unit_code, name, property_type, condo, region, max_guests, suites, beds, bathrooms, short_description, description, amenities, house_rules, check_in_time, check_out_time, cancellation_policy, wifi_ssid, wifi_password, access_method, door_code, access_instructions)
VALUES (cid, 'tamona-18', 'Tamoná 18', 'casa_rooftop', 'Tamoná', 'São Miguel dos Milagres', 6, 2, '2 camas queen + 2 bicama', '2 banheiros', 'Casa com rooftop, piscina privativa e vista para os coqueirais.', 'Casa com rooftop e vista para os coqueirais, ideal para conforto e lazer. Acomoda até 6 pessoas em 2 suítes.', ARRAY['2 suíte(s) com ar-condicionado', 'Sala de TV', 'Internet de alta velocidade em toda a casa', 'Cozinha totalmente equipada', 'Rooftop com piscina privativa', 'Churrasqueira portátil a carvão']::text[], ARRAY['Proibido som alto', 'Proibido animais na piscina', 'Proibido fumar', 'Proibido fazer festas', 'Proibido acumular lixo na acomodação', 'O descumprimento das regras pode gerar multa']::text[], '15:00', '11:00', 'Não reembolsável.', 'TAMONA18', 'tamona18', 'chaves_cofre', NULL, 'Check-in a partir das 15h. As chaves ficam no cofre da acomodação; nossa equipe envia o código pelo WhatsApp. No check-out (11h), recoloque as chaves no cofre.')
ON CONFLICT (company_id, unit_code) DO UPDATE SET
  name = EXCLUDED.name, property_type = EXCLUDED.property_type, condo = EXCLUDED.condo, region = EXCLUDED.region, max_guests = EXCLUDED.max_guests, suites = EXCLUDED.suites, beds = EXCLUDED.beds, bathrooms = EXCLUDED.bathrooms, short_description = EXCLUDED.short_description, description = EXCLUDED.description, amenities = EXCLUDED.amenities, house_rules = EXCLUDED.house_rules, check_in_time = EXCLUDED.check_in_time, check_out_time = EXCLUDED.check_out_time, cancellation_policy = EXCLUDED.cancellation_policy, wifi_ssid = EXCLUDED.wifi_ssid, wifi_password = EXCLUDED.wifi_password, access_method = EXCLUDED.access_method, door_code = EXCLUDED.door_code, access_instructions = EXCLUDED.access_instructions, updated_at = now();

INSERT INTO public.property_guides (company_id, unit_code, name, property_type, condo, region, max_guests, suites, beds, bathrooms, short_description, description, amenities, house_rules, check_in_time, check_out_time, cancellation_policy, wifi_ssid, wifi_password, access_method, door_code, access_instructions)
VALUES (cid, 'villa-green', 'Villa Green', 'casa_terrea', 'Essence', 'São Miguel dos Milagres', 6, 2, '2 camas queen + 2 bicama', '2 banheiros', 'Casa térrea a passos do mar com piscina privativa (Condomínio Essence).', 'Casa térrea a passos do mar, ideal para conforto e lazer. Acomoda até 6 pessoas em 2 suítes. Condomínio Essence, unidade B001.', ARRAY['2 suíte(s) com ar-condicionado', 'Sala de TV', 'Internet de alta velocidade em toda a casa', 'Cozinha totalmente equipada', 'Piscina privativa', 'Churrasqueira portátil a carvão']::text[], ARRAY['Proibido som alto', 'Proibido animais na piscina', 'Proibido fumar', 'Proibido fazer festas', 'Proibido acumular lixo na acomodação', 'O descumprimento das regras pode gerar multa']::text[], '15:00', '11:00', 'Não reembolsável.', 'EssenceB001', 'b001essence', 'chaves_portaria', NULL, 'Check-in a partir das 15h. Retire as chaves na portaria (Condomínio Essence, unidade B001). No check-out (11h), entregue as chaves na portaria.')
ON CONFLICT (company_id, unit_code) DO UPDATE SET
  name = EXCLUDED.name, property_type = EXCLUDED.property_type, condo = EXCLUDED.condo, region = EXCLUDED.region, max_guests = EXCLUDED.max_guests, suites = EXCLUDED.suites, beds = EXCLUDED.beds, bathrooms = EXCLUDED.bathrooms, short_description = EXCLUDED.short_description, description = EXCLUDED.description, amenities = EXCLUDED.amenities, house_rules = EXCLUDED.house_rules, check_in_time = EXCLUDED.check_in_time, check_out_time = EXCLUDED.check_out_time, cancellation_policy = EXCLUDED.cancellation_policy, wifi_ssid = EXCLUDED.wifi_ssid, wifi_password = EXCLUDED.wifi_password, access_method = EXCLUDED.access_method, door_code = EXCLUDED.door_code, access_instructions = EXCLUDED.access_instructions, updated_at = now();

INSERT INTO public.kb_articles (company_id, scope, category, title, content, data, visibility, tags, sort_order)
VALUES (cid, 'region', 'como_chegar', 'Como chegar a São Miguel dos Milagres', 'Os aeroportos mais próximos são Maceió e Recife, ambos com fácil acesso à região (o aeroporto de Maragogi ainda não opera). Indicamos serviços de transfer entre o aeroporto e a acomodação. Para quem vem de carro alugado, siga sempre a localização enviada pela nossa equipe pelo WhatsApp.', NULL, 'public', ARRAY['transfer', 'aeroporto', 'chegada', 'seed:guia_v1']::text[], 10);

INSERT INTO public.kb_articles (company_id, scope, category, title, content, data, visibility, tags, sort_order)
VALUES (cid, 'region', 'checkin', 'Check-in, check-out e cancelamento', 'Check-in a partir das 15h e check-out às 11h. Antes de sair, confira se não esqueceu pertences, desligue equipamentos e ar-condicionado. Para prolongar a estadia, fale conosco com antecedência pelo WhatsApp. Política de cancelamento: não reembolsável. O método de acesso (fechadura facial, chaves na portaria ou cofre) e a senha são enviados ao hóspede com reserva confirmada.', NULL, 'public', ARRAY['checkin', 'checkout', 'cancelamento', 'horario', 'seed:guia_v1']::text[], 20);

INSERT INTO public.kb_articles (company_id, scope, category, title, content, data, visibility, tags, sort_order)
VALUES (cid, 'region', 'enxoval', 'Roupa de cama e banho (enxoval)', 'Oferecemos enxoval completo, ajustado à quantidade de pessoas da reserva. Para estadias com diária mínima de 7 dias, fazemos a troca do enxoval sem custo. Caso alguma peça seja danificada, pode ser aplicada taxa de reposição.', NULL, 'public', ARRAY['enxoval', 'cama', 'banho', 'toalha', 'seed:guia_v1']::text[], 30);

INSERT INTO public.kb_articles (company_id, scope, category, title, content, data, visibility, tags, sort_order)
VALUES (cid, 'region', 'locomocao', 'Como se locomover e estacionamento', 'Há serviços de táxi e transfer na região (podemos recomendar opções confiáveis). A acomodação fica a poucos passos da praia, cerca de 5 minutos de caminhada. O estacionamento fica em frente ao condomínio — use qualquer vaga livre.', NULL, 'public', ARRAY['taxi', 'transfer', 'estacionamento', 'caminhada', 'seed:guia_v1']::text[], 40);

INSERT INTO public.kb_articles (company_id, scope, category, title, content, data, visibility, tags, sort_order)
VALUES (cid, 'region', 'mercados', 'Mercados', 'Opções de supermercados e mercearias na região.', '{"itens": [{"nome": "Supermercado O Amigão (3 unidades)", "endereco": "Após a Avenida do Marceneiro, rua principal — ~7 min de carro", "obs": "Baixe o app do Amigão para preços exclusivos"}, {"nome": "Porto Prime", "endereco": "AL-101, após a peixaria do Neto — poucos minutos", "obs": "Bom para pequenas compras"}, {"nome": "O Predileto", "endereco": "Rua João Pessoa 126, Porto de Pedras (em frente ao Patacho Móveis)", "obs": "Variedade de alta qualidade"}]}'::jsonb, 'public', ARRAY['mercado', 'supermercado', 'compras', 'seed:guia_v1']::text[], 50);

INSERT INTO public.kb_articles (company_id, scope, category, title, content, data, visibility, tags, sort_order)
VALUES (cid, 'region', 'acougues', 'Açougues e frutos do mar', 'Carnes e frutos do mar frescos, vários com entrega.', '{"itens": [{"nome": "Porto Prime", "endereco": "Tatuamunha", "contato": "+55 82 98210-8820"}, {"nome": "Peixaria / Carnes Milagres", "endereco": "Marceneiro, rua principal", "contato": "82 8813-1773"}, {"nome": "Açougue Deus é Fiel", "endereco": "São Miguel dos Milagres", "contato": "82 8157-4709"}, {"nome": "Marítima Frutos do Mar e Carnes", "endereco": "Apenas delivery", "contato": "82 9150-4969"}]}'::jsonb, 'public', ARRAY['acougue', 'carne', 'frutos do mar', 'churrasco', 'seed:guia_v1']::text[], 60);

INSERT INTO public.kb_articles (company_id, scope, category, title, content, data, visibility, tags, sort_order)
VALUES (cid, 'region', 'restaurantes', 'Restaurantes', 'Restaurantes e bares de praia recomendados na Rota Ecológica.', '{"itens": [{"nome": "Mi Casa", "instagram": "@micasapraia", "local": "Praia do Riacho", "obs": "Bar de praia pé na areia"}, {"nome": "Banamí (Pousada Haya)", "instagram": "@pousadahaya", "local": "Praia do Riacho", "obs": "Gastronomia de alto nível"}, {"nome": "Tapioca da Elisângela", "instagram": "@tapiocadaelisangela", "local": "Vilinha Marceneiro"}, {"nome": "Cantinho Nordestino", "instagram": "@cantinhonordestino", "local": "Povoado Tatuamunha"}, {"nome": "Russo Gastrobar", "instagram": "@russogastrobar467", "local": "Povoado Tatuamunha"}, {"nome": "No Tacho", "instagram": "@notacho", "local": "Povoado Tatuamunha"}, {"nome": "Restaurante Tatuá", "instagram": "@pousadatatua", "local": "Povoado Tatuamunha"}, {"nome": "No Quintal", "instagram": "@restaurantenoquintal", "local": "Povoado Toque"}, {"nome": "Villa Italiana", "instagram": "@pousadavillaitaliana", "local": "Porto da Rua"}, {"nome": "Amendoeira", "instagram": "@pousadaamendoeira", "local": "Porto da Rua"}, {"nome": "Enildo Restaurante", "instagram": "@enildorestaurante", "local": "Porto da Rua"}]}'::jsonb, 'public', ARRAY['restaurante', 'comer', 'gastronomia', 'seed:guia_v1']::text[], 70);

INSERT INTO public.kb_articles (company_id, scope, category, title, content, data, visibility, tags, sort_order)
VALUES (cid, 'region', 'cafe_da_manha', 'Café da manhã', 'Lugares para um bom café da manhã na região.', '{"itens": [{"nome": "Delícias Alagoanas", "instagram": "@deliciasalagoanas.milagres", "local": "Vilinha Marceneiro"}, {"nome": "Rota Café", "instagram": "@cafe.rota", "local": "Tatuamunha, Villa Buriti"}, {"nome": "Rancho Paraíso", "instagram": "@ranchoparaiso_pousada", "local": "Tatuamunha"}]}'::jsonb, 'public', ARRAY['cafe', 'cafe da manha', 'breakfast', 'seed:guia_v1']::text[], 80);

INSERT INTO public.kb_articles (company_id, scope, category, title, content, data, visibility, tags, sort_order)
VALUES (cid, 'region', 'vida_noturna', 'Vida noturna', 'Bares e restaurantes para a noite.', '{"itens": [{"nome": "Villa Milagres", "instagram": "@villamilagres", "local": "Porto da Rua", "obs": "Drinks e música ao vivo"}, {"nome": "Na Casa de Boa", "instagram": "@nacasadeboa", "local": "Tatuamunha, ao lado da Vila Guajá", "obs": "Gastrobar ao ar livre"}, {"nome": "Acqua Milagres", "instagram": "@acquamilagres", "local": "Rua da Praia, São Miguel dos Milagres", "obs": "Pé na areia e drinks"}, {"nome": "Praio Milagres", "instagram": "@praiomilagres", "local": "Praia de Porto da Rua", "obs": "Drinks e música ao vivo"}]}'::jsonb, 'public', ARRAY['noite', 'bar', 'drinks', 'musica', 'seed:guia_v1']::text[], 90);

INSERT INTO public.kb_articles (company_id, scope, category, title, content, data, visibility, tags, sort_order)
VALUES (cid, 'region', 'praias', 'Praias', 'Principais praias da região.', '{"itens": [{"nome": "Praia do Riacho", "endereco": "Povoado Riacho — ~4 min da acomodação"}, {"nome": "Praia do Marceneiro", "endereco": "Marceneiro — ~10 min de carro"}, {"nome": "Praia de São Miguel", "endereco": "Cidade de São Miguel dos Milagres — ~10 min"}, {"nome": "Praia de Porto da Rua", "endereco": "Povoado Porto da Rua"}, {"nome": "Praia da Lage", "endereco": "Povoado Lages"}, {"nome": "Praia do Patacho", "endereco": "Povoado Patacho"}]}'::jsonb, 'public', ARRAY['praia', 'mar', 'banho', 'seed:guia_v1']::text[], 100);

INSERT INTO public.kb_articles (company_id, scope, category, title, content, data, visibility, tags, sort_order)
VALUES (cid, 'region', 'passeios', 'Passeios e aventura', 'Passeios recomendados na Rota Ecológica.', '{"itens": [{"nome": "Passeio na Jangamar (águas cristalinas)", "instagram": "@ferreira.tourmilagres"}, {"nome": "Passeio de buggy", "instagram": "@ferreira.tourmilagres", "contato": "(82) 99402-5123"}, {"nome": "Passeio de bike na Rota", "instagram": "@toninho_passeios_bike", "contato": "(82) 98236-0604"}, {"nome": "Quadriciclo / trilha", "instagram": "@trailtourquadriculos", "contato": "(82) 99424-8464"}]}'::jsonb, 'public', ARRAY['passeio', 'buggy', 'jangada', 'trilha', 'bike', 'seed:guia_v1']::text[], 110);

INSERT INTO public.kb_articles (company_id, scope, category, title, content, data, visibility, tags, sort_order)
VALUES (cid, 'region', 'beleza_spa', 'Beleza, spa e massagem', 'Profissionais de beleza e bem-estar na região.', '{"itens": [{"nome": "Mayra Nobre (maquiagem e cabelo)", "instagram": "@mayaranobr"}, {"nome": "Studio Luliriel (spa, cabelo, massagem)", "instagram": "@studioluliriel"}, {"nome": "Hanai Massage (Ricardo — massagem relaxante)", "instagram": "@hanaimassage"}]}'::jsonb, 'public', ARRAY['spa', 'massagem', 'cabelo', 'maquiagem', 'beleza', 'seed:guia_v1']::text[], 120);

INSERT INTO public.kb_articles (company_id, scope, category, title, content, data, visibility, tags, sort_order)
VALUES (cid, 'region', 'imperdiveis', 'Imperdíveis e pontos turísticos', 'Lugares imperdíveis no destino, incluindo pontos gratuitos e beach clubs.', '{"itens": [{"nome": "Capela dos Milagres / Praia do Marceneiro", "obs": "Águas calmas e cristalinas", "contato": "(82) 9341-5995 (agendamento)"}, {"nome": "Vilinha Marceneiro", "obs": "Artesanato e gastronomia local"}, {"nome": "Vila Guajá", "endereco": "Povoado Tatuamunha / Porto de Pedras", "obs": "Restaurantes e artesanato"}, {"nome": "Centro Artesanal Tatuamunha", "endereco": "Tatuamunha / Porto de Pedras", "obs": "Maior centro de artesanato da Rota"}, {"nome": "Ponte do Rio Tatuamunha", "obs": "Vista do encontro do rio com o mar (gratuito)"}, {"nome": "Alto do Cruzeiro de São Miguel", "obs": "Vista do alto da cidade (gratuito)"}, {"nome": "Fonte dos Milagres", "obs": "Símbolo de fé e cura (gratuito)"}, {"nome": "Igreja São Miguel dos Milagres", "obs": "3ª igreja mais antiga de Alagoas (gratuito)"}, {"nome": "Beach clubs: Sonhos do Patacho, Santo Milagres, Milagres do Toque", "obs": "Estrutura completa à beira-mar"}]}'::jsonb, 'public', ARRAY['turismo', 'passeio', 'gratuito', 'beach club', 'igreja', 'seed:guia_v1']::text[], 130);

INSERT INTO public.kb_articles (company_id, scope, category, title, content, data, visibility, tags, sort_order)
VALUES (cid, 'region', 'emergencia', 'Contatos de emergência', 'Números úteis para emergências.', '{"itens": [{"nome": "Polícia Militar", "contato": "190"}, {"nome": "Corpo de Bombeiros", "contato": "193"}, {"nome": "SAMU", "contato": "192"}, {"nome": "Hospital / posto de saúde", "contato": "(82) 99370-4140"}, {"nome": "Farmácia do Trabalhador (Porto da Rua)", "contato": "(82) 99655-5511"}, {"nome": "Farmácia Porto da Rua", "contato": "(82) 9829-5152"}, {"nome": "Farmácia Povoado Lages", "contato": "(82) 99655-2115"}]}'::jsonb, 'public', ARRAY['emergencia', 'hospital', 'policia', 'farmacia', 'samu', 'seed:guia_v1']::text[], 140);

INSERT INTO public.kb_articles (company_id, scope, category, title, content, data, visibility, tags, sort_order)
VALUES (cid, 'region', 'faq', 'Posso levar meu pet?', 'Aceitamos pets de pequeno porte, desde que informados na realização da reserva.', NULL, 'public', ARRAY['faq', 'pet', 'animal', 'seed:guia_v1']::text[], 200);

INSERT INTO public.kb_articles (company_id, scope, category, title, content, data, visibility, tags, sort_order)
VALUES (cid, 'region', 'faq', 'Como me conectar ao Wi-Fi?', 'Todas as acomodações têm Wi-Fi de alta velocidade. A rede e a senha específicas da sua acomodação são enviadas ao hóspede com reserva confirmada.', NULL, 'public', ARRAY['faq', 'wifi', 'internet', 'seed:guia_v1']::text[], 210);

INSERT INTO public.kb_articles (company_id, scope, category, title, content, data, visibility, tags, sort_order)
VALUES (cid, 'region', 'faq', 'Tem estacionamento no local?', 'Sim. O estacionamento fica em frente ao condomínio; use qualquer vaga livre.', NULL, 'public', ARRAY['faq', 'estacionamento', 'carro', 'seed:guia_v1']::text[], 220);

INSERT INTO public.kb_articles (company_id, scope, category, title, content, data, visibility, tags, sort_order)
VALUES (cid, 'region', 'faq', 'Tem roupa de cama e banho?', 'Sim, deixamos enxoval completo para cada hóspede. Realizamos uma troca mediante solicitação para estadias de até 7 noites.', NULL, 'public', ARRAY['faq', 'enxoval', 'cama', 'banho', 'seed:guia_v1']::text[], 230);

END $$;
